import 'package:flutter/material.dart';

class AppTexts {
  static const Map<String, String> _tr = {
    'appName': 'NO SMOKE',
    'selectLanguage': 'Dil Seç',
    'splashTagline': '',
    'initialSurvey': 'Başlangıç Anketi',
    'name': 'Ad',
    'age': 'Yaş',
    'gender': 'Cinsiyet',
    'male': 'Erkek',
    'female': 'Kadın',
    'selectOption': 'Seçiniz',
    'professionLabel': 'Meslek',
    'professionStudent': 'Öğrenci',
    'professionOfficer': 'Memur',
    'professionWorker': 'İşçi',
    'professionHealthcare': 'Sağlık Çalışanı',
    'professionTeacher': 'Öğretmen',
    'professionEngineer': 'Mühendis',
    'professionTradesman': 'Esnaf',
    'professionRetired': 'Emekli',
    'professionFreelance': 'Serbest Çalışıyor',
    'professionOther': 'Diğer',
    'smokingInfo': 'Sigara Bilgileri',
    'firstCigaretteWhen': 'İlk sigara ne zaman?',
    'maxSmokeFreeDuration': 'En fazla ne kadar sigarasız kalabiliyorsunuz?',
    'smokingYears': 'Kaç yıldır sigara içiyorsunuz?',
    'smokingYears1to3': '1-3 yıl',
    'smokingYears4to7': '4-7 yıl',
    'smokingYears8to10': '8-10 yıl',
    'smokingYears10plus': '10+ yıl',
    'lifeRoutine': 'Yaşam Düzeni',
    'sleepTime': 'Uyku saati',
    'wakeTime': 'Uyanma saati',
    'workStart': 'Çalışma başlangıç saati',
    'workEnd': 'Çalışma bitiş saati',
    'workplaceSmoking': 'İş yerinde sigara içilebiliyor mu?',
    'yes': 'Evet',
    'no': 'Hayır',
    'onlyBreaks': 'Sadece molalarda',
    'healthStatus': 'Sağlık Durumu',
    'hypertension': 'Hipertansiyon',
    'asthma': 'Astım',
    'diabetes': 'Diyabet',
    'copd': 'KOAH',
    'heartDisease': 'Kalp Hastalığı',
    'triggerTitle': 'Sigara Tetikleyicileri',
    'triggerCoffee': 'Kahve içerken',
    'triggerMeal': 'Yemek sonrası',
    'triggerDriving': 'Araç kullanırken',
    'triggerStress': 'Stresliyken',
    'triggerPhone': 'Telefonda konuşurken',
    'triggerSocial': 'Sosyal ortamda',
    'triggerAlcohol': 'Alkol kullanırken',
    'stressTitle': 'Stres Seviyesi',
    'stressLow': 'Düşük',
    'stressMedium': 'Orta',
    'stressHigh': 'Yüksek',
    'quitReasonTitle': 'Bırakma Sebebi',
    'quitReason': 'Bırakma sebebi',
    'quitHealth': 'Sağlık',
    'quitFamily': 'Aile',
    'quitMoney': 'Maddi sebepler',
    'quitChildren': 'Çocuklar',
    'quitPerformance': 'Performans',
    'continue': 'Devam Et',
    'trialInfoTitle': '14 Gunluk Ucretsiz Surum Bilgilendirme',
    'trialInfoMessage':
        'Bu program 14 gunluk ucretsiz surum tam erisim olacaktir. Lutfen kurallara uymaya ve programi kullanmaya gayret gosterin. 14 gun sonunda sigara icme sayisinda dusme olduguna ikna olursaniz aylik 1\$ karsiliginda ilerlemenizi gelistirme secenegine sahip olacaksiniz. O yuzden kendinizi bu 14 gun icinde kontrol edin.',
    'breathTest': 'Nefes Testi',
    'test': 'Test',
    'start': 'Başla',
    'iBreathed': 'Nefes Aldım',
    'test1Name': 'Nefes Verme Testi',
    'test2Name': 'Nefes Tutma Testi',
    'test1Instruction':
        'Test 1: Nefesinizi normal şekilde dışarı verin.\n\nİlk nefes alma ihtiyacı hissettiğinizde butona basın.',
    'test2Instruction':
        'Test 2: Derin bir nefes alın ve tutmaya çalışın.\n\nİlk nefes verme ihtiyacı hissettiğinizde butona basın.',
    'riskAnalysis': 'Risk Analizi',
    'hello': 'Merhaba',
    'taskCountToday': 'Bugünkü Görev Sayısı',
    'taskUnit': 'Görev',
    'subscriptionInfo': 'Abonelik Bilgileri',
    'subscriptionType': 'Abonelik Tipi',
    'subscriptionStart': 'Abonelik Başlangıç Tarihi',
    'subscriptionEnd': 'Abonelik Bitiş Tarihi',
    'totalUsage': 'Toplam Kullanım Süresi',
    'trialStatus': 'Deneme Süresi Durumu',
    'premiumActive': 'Premium Özellikler Aktif Mi?',
    'free': 'Ücretsiz',
    'premium': 'Premium',
    'active': 'Aktif',
    'passive': 'Pasif',
    'notSpecified': 'Belirtilmedi',
    'days': 'gün',
    'home': 'Ana Sayfa',
    'welcome': 'Hoş geldin',
    'riskLevel': 'Risk seviyesi',
    'riskScore': 'Risk skoru',
    'lastSurveyDate': 'Son anket tarihi',
    'lastBreathTest': 'Son nefes testi',
    'noRecordYet': 'Henüz kayıt yok',
    'breathTrend': 'Nefes testi gelişimi',
    'daily': 'Günlük',
    'weekly': 'Haftalık',
    'monthly': 'Aylık',
    'chainSmokingTrend': 'Arka arkaya sigara eğilimi',
    'chainSmokingLatest': 'Arka arkaya sigara içme eğilimi',
    'status': 'Son durum',
    'progressRegression': 'Gelişim / gerileme',
    'previousRecord': 'Önceki kayıt',
    'adaptiveSummary': 'Adaptif Ozet',
    'riskyTriggers': 'Riskli tetikleyiciler',
    'riskyHours': 'Riskli saatler',
    'breathImprovementSummary': 'Nefes gelisimi',
    'progressSummary': 'Ilerleme ozeti',
    'predictedRiskTime': 'Tahmini risk zamani',
    'predictedTrigger': 'Tahmini tetikleyici',
    'predictionConfidence': 'Tahmin guveni',
    'weeklyRiskTarget': 'Haftalik risk hedefi',
    'goal180ProgressLabel': '180 gun hedef ilerlemesi',
    'goal180RemainingLabel': '180 gun hedef kalan sure',
    'goal180CadenceLabel': 'Aktif gorevlendirme seviyesi',
    'goal180CadenceOneDay': '1 gunluk gorev sikiligi',
    'goal180CadenceTwoDays': '2 gunluk gorev sikiligi',
    'goal180CadenceWeek': '1 haftalik gorev sikiligi',
    'goal180GuideEarly':
        'Ilk asama: 1 gunluk hedefleri kacirmadan tamamlayin, sistem sizi 180 gunluk plana hazirlar.',
    'goal180GuideMid':
        'Orta asama: 2 gunluk gorev zinciriyle dayaniklilik artiyor. Duzeni bozmayin.',
    'goal180GuideMidHard':
        'Orta asama sikilasti: gorev kacirma artti. 1 gunluk hedefleri eksiksiz tamamlayip tekrar 2 gun seviyesine cikmaniz gerekiyor.',
    'goal180GuideLate':
        'Son asama: 1 haftalik hedefler aktif. 180 gunu tamamlamak icin her gorevi zamaninda bitirin.',
    'goal180GuideLateHard':
        'Son asama kritik: performans dustu. Sistem tekrar 2 gunluk sikiliga cekildi, duzeni geri kazanip 1 haftalik seviyeye donun.',
    'todaysTasks': 'Bugunku gorevler',
    'noTaskToday': 'Bugun icin gorev yok',
    'taskCompleteButton': 'Tamam',
    'taskNotNowButton': 'Simdi Uygun Degil',
    'taskOutcomeQuestion': 'Bu gorevi basariyla tamamladiniz mi?',
    'taskOutcomeYes': 'Evet',
    'taskOutcomeNo': 'Hayir',
    'taskDeferredSaved': 'Gorev ertelendi. 30 dakika sonra tekrar sorulacak.',
    'taskStateNew': 'Durum: Yeni',
    'taskStateCompleted': 'Durum: Tamamlandi',
    'taskStateDeferred': 'Durum: Ertelendi',
    'taskStateFailed': 'Durum: Tamamlanmadi',
    'successfulTaskCount': 'Basarili gorev',
    'failedTaskCount': 'Basarisiz gorev',
    'taskFollowUpTitle': 'Gorev Takip Ekrani',
    'taskFollowUpEmpty': 'Bekleyen gorev takibi yok.',
    'taskFollowUpScheduledAt': 'Planlanan takip saati',
    'taskFollowUpPendingCount': 'Bekleyen takip',
    'openTaskFollowUpScreen': 'Gorev Takip Ekranini Ac',
    'taskDeferredTenMinutes': 'Gorev 10 dakika ertelendi.',
    'taskStartTitle': 'Gorev Hatirlatmasi',
    'taskFollowUpActionYes': 'Evet',
    'taskFollowUpActionNo': 'Hayir',
    'taskActionDoneLabel': 'Tamam',
    'taskActionNotNowLabel': 'Simdi uygun degil',
    'dailyBreathStatus': 'Gunluk nefes testi durumu',
    'breathTestDoneToday': 'Bugun tamamlandi',
    'breathTestPendingToday': 'Bugun henuz yapilmadi',
    'lastExhale': 'Son nefes verme',
    'lastInhale': 'Son nefes tutma',
    'weeklyImprovement': 'Haftalik gelisim etiketi',
    'monthlyImprovement': 'Aylik gelisim etiketi',
    'breathPreviousComparison': 'Bir onceki teste gore',
    'breathAverageComparison': 'Genel ortalamaya gore',
    'breathNoReferenceYet': 'Karsilastirma icin onceki nefes testi yok.',
    'breathComparedPreviousImproved': 'Bir onceki teste gore gelisim',
    'breathComparedPreviousDeclined': 'Bir onceki teste gore gerileme',
    'breathComparedPreviousStable':
        'Bir onceki teste gore belirgin degisim yok.',
    'breathComparedAverageImproved': 'Ortalamaya gore gelisim',
    'breathComparedAverageDeclined': 'Ortalamaya gore gerileme',
    'breathComparedAverageStable': 'Ortalamaya gore belirgin degisim yok.',
    'completeRegistration': 'Kaydı Tamamla',
    'registrationCompleted': 'Kayıt tamamlandı. İlk görev hazırlandı.',
    'firstTaskNoSmoke15': '15 dakika sigara içmeyin.',
    'backToStart': 'Başa Dön',
    'weeklySurvey': 'Haftalık Anket',
    'weeklySavePrompt': 'Bu haftaki durumunuzu kaydedin.',
    'weeklySurveyPromptAsk': 'Haftalık anketi şimdi yapmak ister misiniz?',
    'weeklyMood': 'Haftalık ruh hali',
    'good': 'İyi',
    'bad': 'Kötü',
    'addNote': 'Not ekleyin',
    'save': 'Kaydet',
    'evaluation': 'Değerlendirme',
    'progressPositive': 'İlerleme var, iyi gidiyorsunuz.',
    'progressNegative': 'İlerleme görünmüyor; kendinizi destekleyin.',
    'progressPositiveDetail':
        'Gelişim gösteren alanlar olumlu rapor olarak kaydedildi.',
    'progressNegativeDetail':
        'Bir önceki değerlendirmeye göre gerileme veya değişim yok. Devam edin.',
    'packChangeDaily': 'Günlük paket değişimi',
    'exhaleDelta': 'Nefes verme testi değişimi',
    'inhaleDelta': 'Nefes tutma testi değişimi',
    'riskDelta': 'Risk puanı değişimi',
    'chainSmoking': 'Arka arkaya sigara',
    'firstEvaluation': 'İlk değerlendirme',
    'viewAllSurveys': 'Tüm geçmiş anketleri gör',
    'backToHome': 'Ana sayfaya dön',
    'surveyHistory': 'Anket Geçmişi',
    'noSurveyYet': 'Henüz kayıtlı anket yok.',
    'unnamedUser': 'İsimsiz kullanıcı',
    'risk': 'Risk',
    'packsPerDayQuestion': 'Günde kaç paket sigara içiyorsunuz?',
    'packsApproxQuestion': 'Günde yaklaşık kaç paket içiyorsunuz?',
    'lessThanOnePack': '1 paketten az',
    'onePack': '1 paket',
    'twoPack': '2 paket',
    'threePack': '3 paket',
    'threePlusPack': '3+ paket',
    'fourPack': '4 paket',
    'fivePack': '5 paket',
    'sixPack': '6 paket',
    'sevenPlusPack': '7+ paket',
    'chainSmokingSituation': 'Arka arkaya sigara içme durumu',
    'chainSmokingAsk': 'Arka arkaya sigara içer misiniz?',
    'chainSmokingCountAsk': 'Genellikle arka arkaya kaç sigara içiyorsunuz?',
    'yesSometimes': 'Evet, bazen',
    'yesOften': 'Evet, sık sık',
    'twoCig': '2 adet',
    'threeCig': '3 adet',
    'fourCig': '4 adet',
    'fivePlusCig': '5+ adet',

    'riskDescCritical':
        'Yoğun bağımlılık riski tespit edildi. Program daha sık görev üretecek.',
    'riskDescHigh': 'Yüksek bağımlılık riski tespit edildi.',
    'riskDescMedium': 'Orta seviye bağımlılık riski tespit edildi.',
    'riskDescLow': 'Düşük risk seviyesi tespit edildi.',
    'firstCigarette0to5': '0-5 dakika',
    'firstCigarette5to10': '5-10 dakika',
    'firstCigarette10to30': '10-30 dakika',
    'firstCigarette30to60': '30-60 dakika',
    'firstCigarette60plus': '60 dakika ve üzeri',
    'smokeFree0to15': '0-15 dakika',
    'smokeFree15to30': '15-30 dakika',
    'smokeFree30to60': '30-60 dakika',
    'smokeFree60to120': '1-2 saat',
    'smokeFree120to240': '2-4 saat',
    'smokeFree240plus': '4 saat ve üzeri',
    'secShort': 'sn',
    'pointShort': 'puan',
    'trendStable': 'Stabil',
    'trendImproving': 'Pozitif gelişim',
    'trendDeclining': 'Gerileme',
    'breathTestRecordTitle': 'Nefes Testi',
    'initialRecordTitle': 'Başlangıç Anketi',
    'weeklyRecordTitle': 'Haftalık Anket',
    'riskCritical': 'KRİTİK',
    'riskHigh': 'YÜKSEK',
    'riskMedium': 'ORTA',
    'riskLow': 'DÜŞÜK',
    'validationNameRequired': 'Lütfen ad alanını doldurun.',
    'validationAgeRequired': 'Lütfen yaş alanını doldurun.',
    'validationGenderRequired': 'Lütfen cinsiyet seçin.',
    'validationProfessionRequired': 'Lütfen meslek alanını doldurun.',
    'validationSmokingYearsRequired':
        'Lütfen kaç yıldır sigara içtiğinizi belirtin.',
    'validationChainHabitRequired':
        'Lütfen arka arkaya sigara içme durumunu seçin.',
    'validationChainCountRequired': 'Lütfen arka arkaya sigara adedini seçin.',
    'validationSleepTimeRequired': 'Lütfen uyku saatini seçin.',
    'validationWakeTimeRequired': 'Lütfen uyanma saatini seçin.',
    'validationWorkStartRequired': 'Lütfen çalışma başlangıç saatini girin.',
    'validationWorkEndRequired': 'Lütfen çalışma bitiş saatini girin.',
    'saveErrorRetry': 'Kayıt sırasında bir hata oluştu. Lütfen tekrar deneyin.',
  };

  static const Map<String, String> _en = {
    'appName': 'NO SMOKE',
    'selectLanguage': 'Select Language',
    'splashTagline': '',
    'initialSurvey': 'Initial Survey',
    'name': 'Name',
    'age': 'Age',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'selectOption': 'Select',
    'professionLabel': 'Profession',
    'professionStudent': 'Student',
    'professionOfficer': 'Officer',
    'professionWorker': 'Worker',
    'professionHealthcare': 'Healthcare Worker',
    'professionTeacher': 'Teacher',
    'professionEngineer': 'Engineer',
    'professionTradesman': 'Tradesman',
    'professionRetired': 'Retired',
    'professionFreelance': 'Freelancer',
    'professionOther': 'Other',
    'smokingInfo': 'Smoking Information',
    'firstCigaretteWhen': 'When is your first cigarette?',
    'maxSmokeFreeDuration': 'How long can you stay smoke-free?',
    'smokingYears': 'How many years have you been smoking?',
    'smokingYears1to3': '1-3 years',
    'smokingYears4to7': '4-7 years',
    'smokingYears8to10': '8-10 years',
    'smokingYears10plus': '10+ years',
    'lifeRoutine': 'Daily Routine',
    'sleepTime': 'Sleep time',
    'wakeTime': 'Wake-up time',
    'workStart': 'Work start time',
    'workEnd': 'Work end time',
    'workplaceSmoking': 'Is smoking allowed at work?',
    'yes': 'Yes',
    'no': 'No',
    'onlyBreaks': 'Only on breaks',
    'healthStatus': 'Health Status',
    'hypertension': 'Hypertension',
    'asthma': 'Asthma',
    'diabetes': 'Diabetes',
    'copd': 'COPD',
    'heartDisease': 'Heart Disease',
    'triggerTitle': 'Smoking Triggers',
    'triggerCoffee': 'While drinking coffee',
    'triggerMeal': 'After meals',
    'triggerDriving': 'While driving',
    'triggerStress': 'When stressed',
    'triggerPhone': 'While on the phone',
    'triggerSocial': 'In social settings',
    'triggerAlcohol': 'When drinking alcohol',
    'stressTitle': 'Stress Level',
    'stressLow': 'Low',
    'stressMedium': 'Medium',
    'stressHigh': 'High',
    'quitReasonTitle': 'Quit Reason',
    'quitReason': 'Reason for quitting',
    'quitHealth': 'Health',
    'quitFamily': 'Family',
    'quitMoney': 'Financial reasons',
    'quitChildren': 'Children',
    'quitPerformance': 'Performance',
    'continue': 'Continue',
    'trialInfoTitle': '14-Day Free Trial Information',
    'trialInfoMessage':
        'This program will provide full access for a 14-day free trial. Please try to follow the rules and use the program consistently. If after 14 days you are convinced that your smoking count has decreased, you will have the option to improve your progress for \$1 per month. Please control yourself carefully during these 14 days.',
    'breathTest': 'Breath Test',
    'test': 'Test',
    'start': 'Start',
    'iBreathed': 'I Breathed',
    'test1Name': 'Exhale Test',
    'test2Name': 'Breath-Hold Test',
    'test1Instruction':
        'Test 1: Exhale normally.\n\nPress the button when you feel the first urge to inhale.',
    'test2Instruction':
        'Test 2: Take a deep breath and hold it.\n\nPress the button when you feel the first urge to exhale.',
    'riskAnalysis': 'Risk Analysis',
    'hello': 'Hello',
    'taskCountToday': 'Today\'s Task Count',
    'taskUnit': 'Task',
    'subscriptionInfo': 'Subscription Info',
    'subscriptionType': 'Subscription Type',
    'subscriptionStart': 'Subscription Start Date',
    'subscriptionEnd': 'Subscription End Date',
    'totalUsage': 'Total Usage',
    'trialStatus': 'Trial Status',
    'premiumActive': 'Premium Features Active?',
    'free': 'Free',
    'premium': 'Premium',
    'active': 'Active',
    'passive': 'Inactive',
    'notSpecified': 'Not specified',
    'days': 'days',
    'home': 'Home',
    'welcome': 'Welcome',
    'riskLevel': 'Risk level',
    'riskScore': 'Risk score',
    'lastSurveyDate': 'Last survey date',
    'lastBreathTest': 'Last breath test',
    'noRecordYet': 'No records yet',
    'breathTrend': 'Breath test trend',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'chainSmokingTrend': 'Chain smoking trend',
    'chainSmokingLatest': 'Chain smoking tendency',
    'status': 'Status',
    'progressRegression': 'Improvement / decline',
    'previousRecord': 'Previous record',
    'adaptiveSummary': 'Adaptive Summary',
    'riskyTriggers': 'Risky triggers',
    'riskyHours': 'Risky hours',
    'breathImprovementSummary': 'Breath improvement',
    'progressSummary': 'Progress summary',
    'predictedRiskTime': 'Predicted risk time',
    'predictedTrigger': 'Predicted trigger',
    'predictionConfidence': 'Prediction confidence',
    'weeklyRiskTarget': 'Weekly risk target',
    'goal180ProgressLabel': '180-day goal progress',
    'goal180RemainingLabel': '180-day remaining time',
    'goal180CadenceLabel': 'Active task cadence',
    'goal180CadenceOneDay': '1-day task intensity',
    'goal180CadenceTwoDays': '2-day task intensity',
    'goal180CadenceWeek': '1-week task intensity',
    'goal180GuideEarly':
        'Early phase: complete 1-day goals without skipping, and prepare for the 180-day plan.',
    'goal180GuideMid':
        'Middle phase: your resilience increases with 2-day task chains. Keep consistency.',
    'goal180GuideMidHard':
        'Middle phase tightened: missed tasks increased. Complete 1-day goals fully to return to 2-day level.',
    'goal180GuideLate':
        'Late phase: 1-week goals are active. Finish each task on time to complete 180 days.',
    'goal180GuideLateHard':
        'Late phase critical: performance dropped. The system moved back to 2-day cadence until stability returns.',
    'todaysTasks': "Today's tasks",
    'noTaskToday': 'No task for today',
    'taskCompleteButton': 'Complete',
    'taskNotNowButton': 'Not now',
    'taskOutcomeQuestion': 'Did you complete this task successfully?',
    'taskOutcomeYes': 'Yes',
    'taskOutcomeNo': 'No',
    'taskDeferredSaved':
        'Task deferred. You will be asked again in 30 minutes.',
    'taskStateNew': 'Status: New',
    'taskStateCompleted': 'Status: Completed',
    'taskStateDeferred': 'Status: Deferred',
    'taskStateFailed': 'Status: Failed',
    'successfulTaskCount': 'Successful tasks',
    'failedTaskCount': 'Failed tasks',
    'taskFollowUpTitle': 'Task Follow-up Screen',
    'taskFollowUpEmpty': 'No pending task follow-ups.',
    'taskFollowUpScheduledAt': 'Scheduled follow-up time',
    'taskFollowUpPendingCount': 'Pending follow-ups',
    'openTaskFollowUpScreen': 'Open Task Follow-up Screen',
    'taskDeferredTenMinutes': 'Task deferred by 10 minutes.',
    'taskStartTitle': 'Task Reminder',
    'taskFollowUpActionYes': 'Yes',
    'taskFollowUpActionNo': 'No',
    'taskActionDoneLabel': 'Complete',
    'taskActionNotNowLabel': 'Not now',
    'dailyBreathStatus': 'Daily breath test status',
    'breathTestDoneToday': 'Completed today',
    'breathTestPendingToday': 'Not completed today',
    'lastExhale': 'Last exhale',
    'lastInhale': 'Last inhale',
    'weeklyImprovement': 'Weekly improvement label',
    'monthlyImprovement': 'Monthly improvement label',
    'breathPreviousComparison': 'Compared to previous test',
    'breathAverageComparison': 'Compared to overall average',
    'breathNoReferenceYet': 'No previous breath test available for comparison.',
    'breathComparedPreviousImproved': 'Improvement versus previous test',
    'breathComparedPreviousDeclined': 'Decline versus previous test',
    'breathComparedPreviousStable':
        'No meaningful change versus previous test.',
    'breathComparedAverageImproved': 'Improvement versus average',
    'breathComparedAverageDeclined': 'Decline versus average',
    'breathComparedAverageStable': 'No meaningful change versus average.',
    'completeRegistration': 'Complete Registration',
    'registrationCompleted':
        'Registration completed. Your first task is ready.',
    'firstTaskNoSmoke15': 'Do not smoke for 15 minutes.',
    'backToStart': 'Back to Start',
    'weeklySurvey': 'Weekly Survey',
    'weeklySavePrompt': 'Save your status for this week.',
    'weeklySurveyPromptAsk':
        'Would you like to complete the weekly survey now?',
    'weeklyMood': 'Weekly mood',
    'good': 'Good',
    'bad': 'Bad',
    'addNote': 'Add a note',
    'save': 'Save',
    'evaluation': 'Evaluation',
    'progressPositive': 'You are making progress, well done.',
    'progressNegative': 'No visible progress; keep supporting yourself.',
    'progressPositiveDetail': 'Improved areas were saved as a positive report.',
    'progressNegativeDetail':
        'Compared to the previous assessment there is no improvement or there is decline. Keep going.',
    'packChangeDaily': 'Daily pack change',
    'exhaleDelta': 'Exhale test change',
    'inhaleDelta': 'Inhale-hold test change',
    'riskDelta': 'Risk score change',
    'chainSmoking': 'Chain smoking',
    'firstEvaluation': 'First evaluation',
    'viewAllSurveys': 'View all past surveys',
    'backToHome': 'Back to home',
    'surveyHistory': 'Survey History',
    'noSurveyYet': 'No saved surveys yet.',
    'unnamedUser': 'Unnamed user',
    'risk': 'Risk',
    'packsPerDayQuestion': 'How many packs do you smoke per day?',
    'packsApproxQuestion': 'Approximately how many packs per day?',
    'lessThanOnePack': 'Less than 1 pack',
    'onePack': '1 pack',
    'twoPack': '2 packs',
    'threePack': '3 packs',
    'threePlusPack': '3+ packs',
    'fourPack': '4 packs',
    'fivePack': '5 packs',
    'sixPack': '6 packs',
    'sevenPlusPack': '7+ packs',
    'chainSmokingSituation': 'Chain smoking status',
    'chainSmokingAsk': 'Do you smoke consecutively?',
    'chainSmokingCountAsk':
        'How many cigarettes do you usually smoke consecutively?',
    'yesSometimes': 'Yes, sometimes',
    'yesOften': 'Yes, often',
    'twoCig': '2',
    'threeCig': '3',
    'fourCig': '4',
    'fivePlusCig': '5+',
    'riskDescCritical':
        'High dependence risk detected. The program will generate tasks more frequently.',
    'riskDescHigh': 'High dependence risk detected.',
    'riskDescMedium': 'Medium dependence risk detected.',
    'riskDescLow': 'Low dependence risk detected.',
    'firstCigarette0to5': '0-5 minutes',
    'firstCigarette5to10': '5-10 minutes',
    'firstCigarette10to30': '10-30 minutes',
    'firstCigarette30to60': '30-60 minutes',
    'firstCigarette60plus': '60+ minutes',
    'smokeFree0to15': '0-15 minutes',
    'smokeFree15to30': '15-30 minutes',
    'smokeFree30to60': '30-60 minutes',
    'smokeFree60to120': '1-2 hours',
    'smokeFree120to240': '2-4 hours',
    'smokeFree240plus': '4+ hours',
    'secShort': 'sec',
    'pointShort': 'pt',
    'trendStable': 'Stable',
    'trendImproving': 'Improving',
    'trendDeclining': 'Declining',
    'breathTestRecordTitle': 'Breath Test',
    'initialRecordTitle': 'Initial Survey',
    'weeklyRecordTitle': 'Weekly Survey',
    'riskCritical': 'CRITICAL',
    'riskHigh': 'HIGH',
    'riskMedium': 'MEDIUM',
    'riskLow': 'LOW',
    'validationNameRequired': 'Please fill in the name field.',
    'validationAgeRequired': 'Please fill in the age field.',
    'validationGenderRequired': 'Please select a gender.',
    'validationProfessionRequired': 'Please fill in the profession field.',
    'validationSmokingYearsRequired':
        'Please specify how many years you have been smoking.',
    'validationChainHabitRequired':
        'Please select your consecutive smoking habit.',
    'validationChainCountRequired':
        'Please select the number of consecutive cigarettes.',
    'validationSleepTimeRequired': 'Please select your sleep time.',
    'validationWakeTimeRequired': 'Please select your wake-up time.',
    'validationWorkStartRequired': 'Please enter your work start time.',
    'validationWorkEndRequired': 'Please enter your work end time.',
    'saveErrorRetry': 'An error occurred while saving. Please try again.',
  };

  static final Map<String, Map<String, String>> _data = {
    'tr': _tr,
    'en': _en,
    'de': {
      ..._en,
      'selectLanguage': 'Sprache wählen',
      'trialInfoTitle': '14-Tage Gratisphase Information',
      'trialInfoMessage':
          'Dieses Programm bietet 14 Tage lang vollen Gratiszugang. Bitte halten Sie die Regeln ein und nutzen Sie das Programm regelmassig. Wenn Sie nach 14 Tagen eine Verringerung der Anzahl gerauchter Zigaretten sehen, konnen Sie Ihre Entwicklung fur 1\$ pro Monat weiter verbessern. Kontrollieren Sie sich in diesen 14 Tagen konsequent.',
      'home': 'Startseite',
      'weeklySurvey': 'Wöchentliche Umfrage',
      'riskAnalysis': 'Risikoanalyse',
      'save': 'Speichern',
      'continue': 'Weiter',
      'goal180ProgressLabel': '180-Tage Fortschritt',
      'goal180RemainingLabel': 'Verbleibende Zeit bis 180 Tage',
      'goal180CadenceLabel': 'Aktive Aufgabenstufe',
      'goal180CadenceOneDay': '1-Tages Aufgabenstufe',
      'goal180CadenceTwoDays': '2-Tage Aufgabenstufe',
      'goal180CadenceWeek': '1-Woche Aufgabenstufe',
    },
    'ar': {
      ..._en,
      'selectLanguage': 'اختر اللغة',
      'trialInfoTitle': 'معلومات التجربة المجانية لمدة 14 يوما',
      'trialInfoMessage':
          'هذا البرنامج يوفر وصولا كاملا لمدة 14 يوما مجانا. يرجى الالتزام بالقواعد واستخدام البرنامج بانتظام. اذا اقتنعت بعد 14 يوما بان عدد السجائر قد انخفض، ستتمكن من تطوير تقدمك مقابل 1 دولار شهريا. لذلك اضبط نفسك خلال هذه الفترة.',
      'home': 'الرئيسية',
      'weeklySurvey': 'استبيان أسبوعي',
      'riskAnalysis': 'تحليل المخاطر',
      'save': 'حفظ',
      'continue': 'متابعة',
      'goal180ProgressLabel': 'تقدم هدف 180 يوما',
      'goal180RemainingLabel': 'الوقت المتبقي حتى 180 يوما',
      'goal180CadenceLabel': 'مستوى المهام النشط',
      'goal180CadenceOneDay': 'مستوى مهام يوم واحد',
      'goal180CadenceTwoDays': 'مستوى مهام يومين',
      'goal180CadenceWeek': 'مستوى مهام اسبوع واحد',
    },
    'fr': {
      ..._en,
      'selectLanguage': 'Choisir la langue',
      'trialInfoTitle': 'Information essai gratuit 14 jours',
      'trialInfoMessage':
          'Ce programme offre un acces complet pendant 14 jours gratuits. Merci de respecter les regles et d utiliser le programme regulierement. Si apres 14 jours vous constatez une baisse du nombre de cigarettes, vous pourrez ameliorer votre progression pour 1\$ par mois. Controlez-vous bien pendant ces 14 jours.',
      'home': 'Accueil',
      'weeklySurvey': 'Enquete hebdomadaire',
      'riskAnalysis': 'Analyse du risque',
      'save': 'Enregistrer',
      'continue': 'Continuer',
      'goal180ProgressLabel': 'Progression objectif 180 jours',
      'goal180RemainingLabel': 'Temps restant sur 180 jours',
      'goal180CadenceLabel': 'Niveau actif des taches',
      'goal180CadenceOneDay': 'Niveau taches 1 jour',
      'goal180CadenceTwoDays': 'Niveau taches 2 jours',
      'goal180CadenceWeek': 'Niveau taches 1 semaine',
    },
    'es': {
      ..._en,
      'selectLanguage': 'Seleccionar idioma',
      'trialInfoTitle': 'Informacion de prueba gratuita de 14 dias',
      'trialInfoMessage':
          'Este programa ofrecera acceso completo durante 14 dias gratis. Intente seguir las reglas y usar el programa de forma constante. Si al final de 14 dias confirma que disminuyo su cantidad de cigarrillos, tendra la opcion de mejorar su progreso por 1\$ al mes. Por eso, controlese bien durante estos 14 dias.',
      'home': 'Inicio',
      'weeklySurvey': 'Encuesta semanal',
      'riskAnalysis': 'Analisis de riesgo',
      'save': 'Guardar',
      'continue': 'Continuar',
      'goal180ProgressLabel': 'Progreso meta de 180 dias',
      'goal180RemainingLabel': 'Tiempo restante para 180 dias',
      'goal180CadenceLabel': 'Cadencia activa de tareas',
      'goal180CadenceOneDay': 'Intensidad de tareas de 1 dia',
      'goal180CadenceTwoDays': 'Intensidad de tareas de 2 dias',
      'goal180CadenceWeek': 'Intensidad de tareas de 1 semana',
    },
  };

  static String text(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    final langMap = _data[code] ?? _data['en']!;
    return langMap[key] ?? _data['en']![key] ?? _data['tr']![key] ?? key;
  }
}

extension AppTextsX on BuildContext {
  String t(String key) => AppTexts.text(this, key);
}
