import 'package:flutter/material.dart';

class AppTexts {
  static const Map<String, String> _tr = {
      'appName': 'NO SMOKE',
      'selectLanguage': 'Dil Seç',
      'splashTagline': 'Kırılmış sigara konseptiyle hazırlanmış akıllı bırakma deneyimi',
      'initialSurvey': 'Başlangıç Anketi',
      'name': 'Ad',
      'age': 'Yaş',
      'gender': 'Cinsiyet',
      'male': 'Erkek',
      'female': 'Kadın',
      'smokingInfo': 'Sigara Bilgileri',
      'firstCigaretteWhen': 'İlk sigara ne zaman?',
      'maxSmokeFreeDuration': 'En fazla ne kadar sigarasız kalabiliyorsunuz?',
      'smokingYears': 'Kaç yıldır sigara içiyorsunuz?',
      'lifeRoutine': 'Yaşam Düzeni',
      'sleepTime': 'Uyku saati',
      'wakeTime': 'Uyanma saati',
      'workStart': 'Çalışma başlangıç saati',
      'workEnd': 'Çalışma bitiş saati',
      'workplaceSmoking': 'İş yerinde sigara içilebiliyor mu?',
      'yes': 'Evet',
      'no': 'Hayır',
      'onlyBreaks': 'Sadece molalarda',
      'healthStatus': 'Sağlık Durumu',
      'hypertension': 'Hipertansiyon',
      'asthma': 'Astım',
      'diabetes': 'Diyabet',
      'copd': 'KOAH',
      'heartDisease': 'Kalp Hastalığı',
      'triggerTitle': 'Sigara Tetikleyicileri',
      'triggerCoffee': 'Kahve içerken',
      'triggerMeal': 'Yemek sonrası',
      'triggerDriving': 'Araç kullanırken',
      'triggerStress': 'Stresliyken',
      'triggerPhone': 'Telefonda konuşurken',
      'triggerSocial': 'Sosyal ortamda',
      'triggerAlcohol': 'Alkol kullanırken',
      'stressTitle': 'Stres Seviyesi',
      'stressLow': 'Düşük',
      'stressMedium': 'Orta',
      'stressHigh': 'Yüksek',
      'quitReasonTitle': 'Bırakma Sebebi',
      'quitReason': 'Bırakma sebebi',
      'quitHealth': 'Sağlık',
      'quitFamily': 'Aile',
      'quitMoney': 'Maddi sebepler',
      'quitChildren': 'Çocuklar',
      'quitPerformance': 'Performans',
      'continue': 'Devam Et',
      'breathTest': 'Nefes Testi',
      'test': 'Test',
      'start': 'Başla',
      'iBreathed': 'Nefes Aldım',
      'test1Name': 'Nefes Verme Testi',
      'test2Name': 'Nefes Tutma Testi',
      'test1Instruction': 'Test 1: Nefesinizi normal şekilde dışarı verin.\n\nİlk nefes alma ihtiyacı hissettiğinizde butona basın.',
      'test2Instruction': 'Test 2: Derin bir nefes alın ve tutmaya çalışın.\n\nİlk nefes alma ihtiyacı hissettiğinizde butona basın.',
      'riskAnalysis': 'Risk Analizi',
      'hello': 'Merhaba',
      'taskCountToday': 'Bugünkü Görev Sayısı',
      'taskUnit': 'Görev',
      'subscriptionInfo': 'Abonelik Bilgileri',
      'subscriptionType': 'Abonelik Tipi',
      'subscriptionStart': 'Abonelik Başlangıç Tarihi',
      'subscriptionEnd': 'Abonelik Bitiş Tarihi',
      'totalUsage': 'Toplam Kullanım Süresi',
      'trialStatus': 'Deneme Süresi Durumu',
      'premiumActive': 'Premium Özellikler Aktif Mi?',
      'free': 'Ücretsiz',
      'premium': 'Premium',
      'active': 'Aktif',
      'passive': 'Pasif',
      'notSpecified': 'Belirtilmedi',
      'days': 'gün',
      'home': 'Ana Sayfa',
      'welcome': 'Hoş geldin',
      'riskLevel': 'Risk seviyesi',
      'riskScore': 'Risk skoru',
      'lastSurveyDate': 'Son anket tarihi',
      'lastBreathTest': 'Son nefes testi',
      'noRecordYet': 'Henüz kayıt yok',
      'breathTrend': 'Nefes testi gelişimi',
      'daily': 'Günlük',
      'weekly': 'Haftalık',
      'monthly': 'Aylık',
      'chainSmokingTrend': 'Arka arkaya sigara eğilimi',
      'chainSmokingLatest': 'Arka arkaya sigara içme eğilimi',
      'status': 'Son durum',
      'progressRegression': 'Gelişim / gerileme',
      'previousRecord': 'Önceki kayıt',
      'adaptiveSummary': 'Adaptif Ozet',
      'riskyTriggers': 'Riskli tetikleyiciler',
      'riskyHours': 'Riskli saatler',
      'breathImprovementSummary': 'Nefes gelisimi',
      'progressSummary': 'Ilerleme ozeti',
      'predictedRiskTime': 'Tahmini risk zamani',
      'predictedTrigger': 'Tahmini tetikleyici',
      'predictionConfidence': 'Tahmin guveni',
      'weeklyRiskTarget': 'Haftalik risk hedefi',
      'todaysTasks': 'Bugunku gorevler',
      'noTaskToday': 'Bugun icin gorev yok',
      'backToStart': 'Başa Dön',
      'weeklySurvey': 'Haftalık Anket',
      'weeklySavePrompt': 'Bu haftaki durumunuzu kaydedin.',
      'weeklyMood': 'Haftalık ruh hali',
      'good': 'İyi',
      'bad': 'Kötü',
      'addNote': 'Not ekleyin',
      'save': 'Kaydet',
      'evaluation': 'Değerlendirme',
      'progressPositive': 'İlerleme var, iyi gidiyorsunuz.',
      'progressNegative': 'İlerleme görünmüyor; kendinizi destekleyin.',
      'progressPositiveDetail': 'Gelişim gösteren alanlar olumlu rapor olarak kaydedildi.',
      'progressNegativeDetail': 'Bir önceki değerlendirmeye göre gerileme veya değişim yok. Devam edin.',
      'packChangeDaily': 'Günlük paket değişimi',
      'exhaleDelta': 'Nefes verme testi değişimi',
      'inhaleDelta': 'Nefes tutma testi değişimi',
      'riskDelta': 'Risk puanı değişimi',
      'chainSmoking': 'Arka arkaya sigara',
      'firstEvaluation': 'İlk değerlendirme',
      'viewAllSurveys': 'Tüm geçmiş anketleri gör',
      'backToHome': 'Ana sayfaya dön',
      'surveyHistory': 'Anket Geçmişi',
      'noSurveyYet': 'Henüz kayıtlı anket yok.',
      'unnamedUser': 'İsimsiz kullanıcı',
      'risk': 'Risk',
      'packsPerDayQuestion': 'Günde kaç paket sigara içiyorsunuz?',
      'packsApproxQuestion': 'Günde yaklaşık kaç paket içiyorsunuz?',
      'lessThanOnePack': '1 paketten az',
      'onePack': '1 paket',
      'twoPack': '2 paket',
      'threePack': '3 paket',
      'threePlusPack': '3+ paket',
      'fourPack': '4 paket',
      'fivePack': '5 paket',
      'sixPack': '6 paket',
      'sevenPlusPack': '7+ paket',
      'chainSmokingSituation': 'Arka arkaya sigara içme durumu',
      'chainSmokingAsk': 'Arka arkaya sigara içer misiniz?',
      'chainSmokingCountAsk': 'Genellikle arka arkaya kaç sigara içiyorsunuz?',
      'yesSometimes': 'Evet, bazen',
      'yesOften': 'Evet, sık sık',
      'twoCig': '2 adet',
      'threeCig': '3 adet',
      'fourCig': '4 adet',
      'fivePlusCig': '5+ adet',
      
      'riskDescCritical': 'Yoğun bağımlılık riski tespit edildi. Program daha sık görev üretecek.',
      'riskDescHigh': 'Yüksek bağımlılık riski tespit edildi.',
      'riskDescMedium': 'Orta seviye bağımlılık riski tespit edildi.',
      'riskDescLow': 'Düşük risk seviyesi tespit edildi.',
      'firstCigarette0to5': '0-5 dakika',
      'firstCigarette5to10': '5-10 dakika',
      'firstCigarette10to30': '10-30 dakika',
      'firstCigarette30to60': '30-60 dakika',
      'firstCigarette60plus': '60 dakika ve üzeri',
      'smokeFree0to15': '0-15 dakika',
      'smokeFree15to30': '15-30 dakika',
      'smokeFree30to60': '30-60 dakika',
      'smokeFree60to120': '1-2 saat',
      'smokeFree120to240': '2-4 saat',
      'smokeFree240plus': '4 saat ve üzeri',
      'secShort': 'sn',
      'pointShort': 'puan',
      'trendStable': 'Stabil',
      'trendImproving': 'Pozitif gelişim',
      'trendDeclining': 'Gerileme',
      'breathTestRecordTitle': 'Nefes Testi',
      'initialRecordTitle': 'Başlangıç Anketi',
      'weeklyRecordTitle': 'Haftalık Anket',
      'riskCritical': 'KRİTİK',
      'riskHigh': 'YÜKSEK',
      'riskMedium': 'ORTA',
      'riskLow': 'DÜŞÜK',
    };

  static const Map<String, String> _en = {
    'appName': 'NO SMOKE',
    'selectLanguage': 'Select Language',
    'splashTagline': 'Smart quit experience inspired by the broken-cigarette concept',
    'initialSurvey': 'Initial Survey',
    'name': 'Name',
    'age': 'Age',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'smokingInfo': 'Smoking Information',
    'firstCigaretteWhen': 'When is your first cigarette?',
    'maxSmokeFreeDuration': 'How long can you stay smoke-free?',
    'smokingYears': 'How many years have you been smoking?',
    'lifeRoutine': 'Daily Routine',
    'sleepTime': 'Sleep time',
    'wakeTime': 'Wake-up time',
    'workStart': 'Work start time',
    'workEnd': 'Work end time',
    'workplaceSmoking': 'Is smoking allowed at work?',
    'yes': 'Yes',
    'no': 'No',
    'onlyBreaks': 'Only on breaks',
    'healthStatus': 'Health Status',
    'hypertension': 'Hypertension',
    'asthma': 'Asthma',
    'diabetes': 'Diabetes',
    'copd': 'COPD',
    'heartDisease': 'Heart Disease',
    'triggerTitle': 'Smoking Triggers',
    'triggerCoffee': 'While drinking coffee',
    'triggerMeal': 'After meals',
    'triggerDriving': 'While driving',
    'triggerStress': 'When stressed',
    'triggerPhone': 'While on the phone',
    'triggerSocial': 'In social settings',
    'triggerAlcohol': 'When drinking alcohol',
    'stressTitle': 'Stress Level',
    'stressLow': 'Low',
    'stressMedium': 'Medium',
    'stressHigh': 'High',
    'quitReasonTitle': 'Quit Reason',
    'quitReason': 'Reason for quitting',
    'quitHealth': 'Health',
    'quitFamily': 'Family',
    'quitMoney': 'Financial reasons',
    'quitChildren': 'Children',
    'quitPerformance': 'Performance',
    'continue': 'Continue',
    'breathTest': 'Breath Test',
    'test': 'Test',
    'start': 'Start',
    'iBreathed': 'I Breathed',
    'test1Name': 'Exhale Test',
    'test2Name': 'Breath-Hold Test',
    'test1Instruction': 'Test 1: Exhale normally.\n\nPress the button when you feel the first urge to inhale.',
    'test2Instruction': 'Test 2: Take a deep breath and hold it.\n\nPress the button when you feel the first urge to inhale.',
    'riskAnalysis': 'Risk Analysis',
    'hello': 'Hello',
    'taskCountToday': 'Today\'s Task Count',
    'taskUnit': 'Task',
    'subscriptionInfo': 'Subscription Info',
    'subscriptionType': 'Subscription Type',
    'subscriptionStart': 'Subscription Start Date',
    'subscriptionEnd': 'Subscription End Date',
    'totalUsage': 'Total Usage',
    'trialStatus': 'Trial Status',
    'premiumActive': 'Premium Features Active?',
    'free': 'Free',
    'premium': 'Premium',
    'active': 'Active',
    'passive': 'Inactive',
    'notSpecified': 'Not specified',
    'days': 'days',
    'home': 'Home',
    'welcome': 'Welcome',
    'riskLevel': 'Risk level',
    'riskScore': 'Risk score',
    'lastSurveyDate': 'Last survey date',
    'lastBreathTest': 'Last breath test',
    'noRecordYet': 'No records yet',
    'breathTrend': 'Breath test trend',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'chainSmokingTrend': 'Chain smoking trend',
    'chainSmokingLatest': 'Chain smoking tendency',
    'status': 'Status',
    'progressRegression': 'Improvement / decline',
    'previousRecord': 'Previous record',
    'adaptiveSummary': 'Adaptive Summary',
    'riskyTriggers': 'Risky triggers',
    'riskyHours': 'Risky hours',
    'breathImprovementSummary': 'Breath improvement',
    'progressSummary': 'Progress summary',
    'predictedRiskTime': 'Predicted risk time',
    'predictedTrigger': 'Predicted trigger',
    'predictionConfidence': 'Prediction confidence',
    'weeklyRiskTarget': 'Weekly risk target',
    'todaysTasks': "Today's tasks",
    'noTaskToday': 'No task for today',
    'backToStart': 'Back to Start',
    'weeklySurvey': 'Weekly Survey',
    'weeklySavePrompt': 'Save your status for this week.',
    'weeklyMood': 'Weekly mood',
    'good': 'Good',
    'bad': 'Bad',
    'addNote': 'Add a note',
    'save': 'Save',
    'evaluation': 'Evaluation',
    'progressPositive': 'You are making progress, well done.',
    'progressNegative': 'No visible progress; keep supporting yourself.',
    'progressPositiveDetail': 'Improved areas were saved as a positive report.',
    'progressNegativeDetail': 'Compared to the previous assessment there is no improvement or there is decline. Keep going.',
    'packChangeDaily': 'Daily pack change',
    'exhaleDelta': 'Exhale test change',
    'inhaleDelta': 'Inhale-hold test change',
    'riskDelta': 'Risk score change',
    'chainSmoking': 'Chain smoking',
    'firstEvaluation': 'First evaluation',
    'viewAllSurveys': 'View all past surveys',
    'backToHome': 'Back to home',
    'surveyHistory': 'Survey History',
    'noSurveyYet': 'No saved surveys yet.',
    'unnamedUser': 'Unnamed user',
    'risk': 'Risk',
    'packsPerDayQuestion': 'How many packs do you smoke per day?',
    'packsApproxQuestion': 'Approximately how many packs per day?',
    'lessThanOnePack': 'Less than 1 pack',
    'onePack': '1 pack',
    'twoPack': '2 packs',
    'threePack': '3 packs',
    'threePlusPack': '3+ packs',
    'fourPack': '4 packs',
    'fivePack': '5 packs',
    'sixPack': '6 packs',
    'sevenPlusPack': '7+ packs',
    'chainSmokingSituation': 'Chain smoking status',
    'chainSmokingAsk': 'Do you smoke consecutively?',
    'chainSmokingCountAsk': 'How many cigarettes do you usually smoke consecutively?',
    'yesSometimes': 'Yes, sometimes',
    'yesOften': 'Yes, often',
    'twoCig': '2',
    'threeCig': '3',
    'fourCig': '4',
    'fivePlusCig': '5+',
    'riskDescCritical': 'High dependence risk detected. The program will generate tasks more frequently.',
    'riskDescHigh': 'High dependence risk detected.',
    'riskDescMedium': 'Medium dependence risk detected.',
    'riskDescLow': 'Low dependence risk detected.',
    'firstCigarette0to5': '0-5 minutes',
    'firstCigarette5to10': '5-10 minutes',
    'firstCigarette10to30': '10-30 minutes',
    'firstCigarette30to60': '30-60 minutes',
    'firstCigarette60plus': '60+ minutes',
    'smokeFree0to15': '0-15 minutes',
    'smokeFree15to30': '15-30 minutes',
    'smokeFree30to60': '30-60 minutes',
    'smokeFree60to120': '1-2 hours',
    'smokeFree120to240': '2-4 hours',
    'smokeFree240plus': '4+ hours',
    'secShort': 'sec',
    'pointShort': 'pt',
    'trendStable': 'Stable',
    'trendImproving': 'Improving',
    'trendDeclining': 'Declining',
    'breathTestRecordTitle': 'Breath Test',
    'initialRecordTitle': 'Initial Survey',
    'weeklyRecordTitle': 'Weekly Survey',
    'riskCritical': 'CRITICAL',
    'riskHigh': 'HIGH',
    'riskMedium': 'MEDIUM',
    'riskLow': 'LOW',
  };

  static final Map<String, Map<String, String>> _data = {
    'tr': _tr,
    'en': _en,
    'de': {..._en, 'selectLanguage': 'Sprache wählen', 'home': 'Startseite', 'weeklySurvey': 'Wöchentliche Umfrage', 'riskAnalysis': 'Risikoanalyse', 'save': 'Speichern', 'continue': 'Weiter'},
    'ar': {..._en, 'selectLanguage': 'اختر اللغة', 'home': 'الرئيسية', 'weeklySurvey': 'استبيان أسبوعي', 'riskAnalysis': 'تحليل المخاطر', 'save': 'حفظ', 'continue': 'متابعة'},
    'fr': {..._en, 'selectLanguage': 'Choisir la langue', 'home': 'Accueil', 'weeklySurvey': 'Enquete hebdomadaire', 'riskAnalysis': 'Analyse du risque', 'save': 'Enregistrer', 'continue': 'Continuer'},
    'es': {..._en, 'selectLanguage': 'Seleccionar idioma', 'home': 'Inicio', 'weeklySurvey': 'Encuesta semanal', 'riskAnalysis': 'Analisis de riesgo', 'save': 'Guardar', 'continue': 'Continuar'},
  };

  static String text(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    final langMap = _data[code] ?? _data['en']!;
    return langMap[key] ?? _data['en']![key] ?? _data['tr']![key] ?? key;
  }
}

extension AppTextsX on BuildContext {
  String t(String key) => AppTexts.text(this, key);
}